import Head from "next/head";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import MovieContentListWrap from "../components/MovieContentListWrap";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Watcha Pedia Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div style={{ marginTop: "82px" }}>
        <MovieContentListWrap />
      </div>
      <Footer />
    </div>
  );
}
